default:
  key: <%= ENV.fetch('IKYUSAN_TWITTER_KEY', 'dummy_key')
  secret: <%= ENV.fetch('IKYUSAN_TWITTER_SECRET', 'dummy_secret')

production:
  key: <%= ENV.fetch('IKYUSAN_TWITTER_KEY', 'dummy_key')
  secret: <%= ENV.fetch('IKYUSAN_TWITTER_SECRET', 'dummy_secret')
